# Generated by Django 4.0.5 on 2022-06-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('degree', models.PositiveSmallIntegerField()),
                ('course_type', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], max_length=20)),
            ],
        ),
    ]
